OENIK_PROG4_2021_1_V6VBEZ/PublicTransportMVC/Models/Employee.cs
namespace PublicTransport.MVC.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// This class represents an Employee in the UI.
    /// </summary>
    public class Employee
    {
        /// <summary>
        /// Gets or sets the EmployeeID of an Employee entity, which is a identifier of an employee.
        /// </summary>
        [Display(Name = "Employee ID Number")]
        [StringLength(8, MinimumLength = 8)]
        public string EmployeeId { get; set; }

        /// <summary>
        /// Gets or sets the Type of an Employee entity, which indicates the job type of the employee.
        /// </summary>
        [Display(Name = "Employee Job")]
        [Required]
        public JobType Type { get; set; }

        /// <summary>
        /// Gets or sets the Name of an Employee entity.
        /// </summary>
        [Display(Name = "Employee Name")]
        [Required]
        [StringLength(60, MinimumLength = 3)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the Date of birth of an Employee entity.
        /// </summary>
        [Display(Name = "Employee Date of birth ")]
        [Required]
        public DateTime DateOfBirth { get; set; }

        /// <summary>
        /// Gets or sets the HireDate of an Employee entity, which indicates the date when the employee started working for the company.
        /// </summary>
        [Display(Name = "Date of hiring ")]
        [Required]
        public DateTime HireDate { get; set; }

        /// <summary>
        /// Gets or sets the wage of an Employee entity, which indicates the salary of the employee.
        /// </summary>
        [Display(Name = "Employee Salary ")]
        [Required]
        public int Wage { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            return $"Employee Id:{this.EmployeeId}, Name:{this.Name}, Date of birth: {this.DateOfBirth.ToShortDateString()}, Type:{this.Type.ToString()}, Hire date:{this.HireDate.ToShortDateString()}, Wage:{this.Wage} ;";
        }
    }
}

OENIK_PROG4_2021_1_V6VBEZ/PublicTransportMVC/Controllers/EmployeesController.cs
namespace PublicTransport.MVC.Controllers
{
    using System;
    using System.Collections.Generic;
    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using PublicTransport.Logic;
    using PublicTransport.MVC.Models;

    /// <summary>
    /// The MVC controller class of employees.
    /// </summary>
    public class EmployeesController : Controller
    {
        private IHumanResourceLogic logic;
        private IMapper mapper;
        private EmployeeListViewModel viewModel;

        /// <summary>
        /// Initializes a new instance of the <see cref="EmployeesController"/> class.
        /// </summary>
        /// <param name="logic">An IHumanResourceLogic implementation.</param>
        /// <param name="mapper">An IMapper implementation. </param>
        public EmployeesController(IHumanResourceLogic logic, IMapper mapper)
        {
            this.logic = logic;
            this.mapper = mapper;

            this.viewModel = new EmployeeListViewModel();
            this.viewModel.EditedEmployee = new Models.Employee();

            IList<Data.Models.Employee> employees = logic?.GetAllEmployee();
            this.viewModel.Employees = mapper?.Map<IList<Data.Models.Employee>, List<MVC.Models.Employee>>(employees);
        }

        /// <summary>
        /// The main page of the website.
        /// </summary>
        /// <returns>The EmployeesIndex view. </returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("EmployeesIndex", this.viewModel);
        }

        /// <summary>
        /// Shows the Details view.
        /// </summary>
        /// <param name="id">The identifier of the employee. </param>
        /// <returns>The EmployeesDetails view.</returns>
        // GET Employees/Details
        public IActionResult Details(string id)
        {
            return this.View("EmployeesDetails", this.GetEmployeeModel(id));
        }

        /// <summary>
        /// Removes the selected employee.
        /// </summary>
        /// <param name="id">The identifier of the employee. </param>
        /// <returns>The EmployeesIndex view. </returns>
        // GET Employees/Remove
        public IActionResult Remove(string id)
        {
            this.TempData["editResult"] = "DeleteFaild";
            if (this.logic.RemoveEmployee(id))
            {
                this.TempData["editResult"] = "Delete OK";
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// This method fils the Index page with datas.
        /// </summary>
        /// <param name="id">The identifier of the employee.</param>
        /// <returns>The EmployeesIndex view.</returns>
        // GET Employees/Edit
        public IActionResult Edit(string id)
        {
            this.ViewData["editAction"] = "Edit";
            this.viewModel.EditedEmployee = this.GetEmployeeModel(id);
            return this.View("EmployeesIndex", this.viewModel);
        }

        /// <summary>
        /// This method refresh the datas of an employee with same identifier.
        /// </summary>
        /// <param name="employee">The employe which we want to edit.</param>
        /// <param name="editAction">It specifies that we want to add or edit an employee.</param>
        /// <returns>The EmployeesIndex view.</returns>
        // POST Employees/Edit
        [HttpPost]
        public IActionResult Edit(Models.Employee employee, string editAction)
        {
            if (this.ModelState.IsValid && employee != null)
            {
                this.TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    try
                    {
                        this.logic.NewEmployee(this.mapper.Map<MVC.Models.Employee, Data.Models.Employee>(employee));
                        this.TempData["editResult"] = "Add OK";
                    }
                    catch (ArgumentException e)
                    {
                        this.TempData["editResult"] = "AddEmployee FAILED " + e.Message;
                    }
                }
                else
                {
                    try
                    {
                        var emp = this.GetEmployeeModel(employee.EmployeeId);
                        if (emp.Name != employee.Name)
                        {
                            this.logic.ChangeName(emp.EmployeeId, employee.Name);
                        }

                        if (emp.Type != employee.Type)
                        {
                            this.logic.ChangePositon(emp.EmployeeId, employee.Type.ToString());
                        }

                        if (emp.Wage != employee.Wage)
                        {
                            this.logic.ChangeWage(emp.EmployeeId, employee.Wage);
                        }
                    }
                    catch (Exception e)
                    {
                        this.TempData["editResult"] = "Edit FAILED " + e.Message;
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.viewModel.EditedEmployee = employee;
                return this.View("EmployeesIndex", this.viewModel);
            }
        }

        private Models.Employee GetEmployeeModel(string id)
        {
            Data.Models.Employee employee = this.logic.GetById(id);
            return this.mapper.Map<Data.Models.Employee, MVC.Models.Employee>(employee);
        }
    }
}

OENIK_PROG4_2021_1_V6VBEZ/PublicTransportMVC/Views/Employees/EmployeesDetails.cshtml
@model PublicTransport.MVC.Models.Employee

@{
    ViewData["Title"] = "EmployeesDetails";

}

<h2>Datasheet of an employee. </h2>

@Html.ActionLink("Back to the list of employees.", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.EmployeeId)</td>
        <td>@Html.DisplayFor(m => m.EmployeeId)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Type)</td>
        <td>@Html.DisplayFor(m => m.Type)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Wage)</td>
        <td>@Html.DisplayFor(m => m.Wage)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.DateOfBirth)</td>
        <td>@Html.DisplayFor(m => m.DateOfBirth)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.HireDate)</td>
        <td>@Html.DisplayFor(m => m.HireDate)</td>
    </tr>
</table>

OENIK_PROG4_2021_1_V6VBEZ/PublicTransportMVC/Views/Employees/EmployeesEdit.cshtml
@model PublicTransport.MVC.Models.Employee

<h2>Employee editor. </h2>

@using (Html.BeginForm("Edit", "Employees"))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.EmployeeId)
    @Html.HiddenFor(m => m.DateOfBirth)
    @Html.HiddenFor(m => m.HireDate)
    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Type)</div>
    <div class="editor-field">@Html.DropDownListFor(m => m.Type, new SelectList(Enum.GetNames(typeof(JobType))))</div>

    <div class="editor-label">@Html.LabelFor(m => m.Wage)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Wage)</div>

    <input type="submit" value="SEND" />
}

OENIK_PROG4_2021_1_V6VBEZ/PublicTransportMVC/Views/Employees/EmployeesIndex.cshtml
@model PublicTransport.MVC.Models.EmployeeListViewModel

@{
    ViewData["Title"] = "Employees Index";
}

<h2> Employees Index </h2>

<p style="color:red">@TempData["editResult"]</p>

@if (Model.EditedEmployee.EmployeeId == null)
{
    @await Html.PartialAsync("EmployeesNew", Model.EditedEmployee);
}
else
{
    @await Html.PartialAsync("EmployeesEdit", Model.EditedEmployee);
}
@await Html.PartialAsync("EmployeesList", Model.Employees)

OENIK_PROG4_2021_1_V6VBEZ/PublicTransportMVC/Views/Employees/EmployeesList.cshtml
@model IEnumerable<PublicTransport.MVC.Models.Employee>

<h2>Empolyees List</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database. </p>
}
else
{
<table border="1">
    <tr>
        <th>@Html.DisplayNameFor(m => m.FirstOrDefault().EmployeeId)</th>
        <th>@Html.DisplayNameFor(m => m.FirstOrDefault().Name)</th>
        <th>Datasheet</th>
        <th>Delete</th>
        <th>Modify</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@Html.DisplayFor(m => item.EmployeeId)</th>
            <th>@Html.DisplayFor(m => item.Name)</th>
            <th>@Html.ActionLink("[SHOW]", "Details", new { Id = item.EmployeeId })</th>
            <th>@Html.ActionLink("[DEL]", "Remove", new { Id = item.EmployeeId })</th>
            <th>@Html.ActionLink("[EDIT]", "Edit", new { Id = item.EmployeeId })</th>
        </tr>
    }
</table>
}

OENIK_PROG4_2021_1_V6VBEZ/PublicTransportMVC/Views/Employees/EmployeesNew.cshtml
@model PublicTransport.MVC.Models.Employee

<h2> Add Employee </h2>

@using (Html.BeginForm("Edit", "Employees"))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.EmployeeId)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EmployeeId)</div>

    <div class="editor-label">@Html.LabelFor(m => m.DateOfBirth)</div>
    <div class="editor-field">@Html.EditorFor(m => m.DateOfBirth)</div>

    <div class="editor-label">@Html.LabelFor(m => m.HireDate)</div>
    <div class="editor-field">@Html.EditorFor(m => m.HireDate)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Type)</div>
    <div class="editor-field">@Html.DropDownListFor(m => m.Type, new SelectList(Enum.GetNames(typeof(JobType))))</div>

    <div class="editor-label">@Html.LabelFor(m => m.Wage)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Wage)</div>

    <input type="submit" value="SEND" />
}